#!/usr/bin/env python3
"""Fit per-host R-calibration from a --per-sv-resid-log CSV.

Reads the per-SV CSV produced by --per-sv-resid-log, computes robust
σ statistics per (sys, elev_bin), and writes a TOML calibration file
that drops into the engine via --r-calibration <path>.

Uses median absolute deviation (MAD × 1.4826) as the σ estimate so
the per-SV outliers documented in 2026-05-21 perSvResidLog work
(G18, E13) don't poison the fit.

Usage:
    fit_r_calibration.py --input <per-sv-csv> --output <toml>
        [--start <iso>] [--min-samples 100] [--pr-floor 0.05]
        [--td-floor 0.003]
"""
from __future__ import annotations

import argparse
import csv
import math
from datetime import datetime
from pathlib import Path

import numpy as np


_DEFAULT_BIN_EDGES = (10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 90.0)


def _mad_sigma(arr: np.ndarray) -> float:
    """MAD × 1.4826 (consistent estimator of σ for Gaussian data,
    robust to ~50% outliers)."""
    if len(arr) < 4:
        return 0.0
    m = np.median(arr)
    return float(1.4826 * np.median(np.abs(arr - m)))


def fit_from_csv(path: Path, start_iso: str | None = None,
                 min_samples: int = 100,
                 bin_edges: tuple[float, ...] = _DEFAULT_BIN_EDGES):
    """Bin (sys, elev) residuals from per-SV CSV; return per-system table.

    Returns: {sys: {'edges': edges, 'sigma_pr_m': [...], 'sigma_td_m': [...]}}
    """
    start_unix = (datetime.fromisoformat(start_iso).timestamp()
                  if start_iso else 0.0)
    rows: list[tuple[str, float, float, float]] = []
    with open(path) as f:
        for r in csv.DictReader(f):
            try:
                eu = float(r['epoch_unix'])
                if eu < start_unix:
                    continue
                sys_ = r['sys']
                elev = float(r['elev_deg'])
                pr = float(r['resid_pr_m'])
                td_s = r.get('resid_td_m', 'nan').strip()
                try:
                    td = float(td_s)
                except ValueError:
                    td = math.nan
                rows.append((sys_, elev, pr, td))
            except (ValueError, KeyError):
                continue

    out = {}
    for sys_ in ('gps', 'gal', 'bds'):
        sigma_pr_m = []
        sigma_td_m = []
        any_bin = False
        for i in range(len(bin_edges) - 1):
            lo, hi = bin_edges[i], bin_edges[i + 1]
            pr_vals, td_vals = [], []
            for s, el, pr, td in rows:
                if s != sys_:
                    continue
                if not (lo <= el < hi):
                    continue
                pr_vals.append(pr)
                if not math.isnan(td):
                    td_vals.append(td)
            if len(pr_vals) >= min_samples:
                sigma_pr_m.append(round(_mad_sigma(np.asarray(pr_vals)), 4))
                any_bin = True
            else:
                sigma_pr_m.append(0.0)  # 0 → fall back to default in lookup
            if len(td_vals) >= min_samples:
                sigma_td_m.append(round(_mad_sigma(np.asarray(td_vals)), 4))
            else:
                sigma_td_m.append(0.0)
        if any_bin:
            out[sys_] = {
                'edges': bin_edges,
                'sigma_pr_m': sigma_pr_m,
                'sigma_td_m': sigma_td_m,
                'n_rows': sum(1 for s, *_ in rows if s == sys_),
            }
    return out


def render_toml(fits, pr_floor_m: float = 0.05,
                td_floor_m: float = 0.003,
                source_note: str = "") -> str:
    lines = []
    lines.append("# R-matrix calibration for FixedPosFilter.")
    lines.append("# Generated by scripts/peppar_fix/fit_r_calibration.py")
    if source_note:
        for line in source_note.split('\n'):
            lines.append(f"# {line}")
    lines.append("")
    lines.append(f"pr_floor_m = {pr_floor_m}")
    lines.append(f"td_floor_m = {td_floor_m}")
    lines.append("")
    for sys_, fit in fits.items():
        lines.append(f"[{sys_}]")
        lines.append(f"# n_rows = {fit['n_rows']}")
        lines.append(f"elev_bins_deg = {list(fit['edges'])}")
        lines.append(f"sigma_pr_m    = {fit['sigma_pr_m']}")
        lines.append(f"sigma_td_m    = {fit['sigma_td_m']}")
        lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, type=Path,
                    help="--per-sv-resid-log CSV")
    ap.add_argument("--output", required=True, type=Path,
                    help="Output TOML path")
    ap.add_argument("--start", default=None,
                    help="ISO UTC start time (skip earlier rows)")
    ap.add_argument("--min-samples", type=int, default=100)
    ap.add_argument("--pr-floor", type=float, default=0.05,
                    help="Minimum σ_pr allowed (m); below this falls "
                         "back to default formula")
    ap.add_argument("--td-floor", type=float, default=0.003,
                    help="Minimum σ_td allowed (m)")
    args = ap.parse_args()

    fits = fit_from_csv(args.input, start_iso=args.start,
                        min_samples=args.min_samples)
    note = (f"source: {args.input.name}\n"
            f"start:  {args.start or 'all rows'}\n"
            f"min_samples_per_bin: {args.min_samples}")
    toml = render_toml(fits, pr_floor_m=args.pr_floor,
                       td_floor_m=args.td_floor, source_note=note)
    args.output.write_text(toml)
    print(f"Wrote {args.output}")
    for sys_, fit in fits.items():
        print(f"\n[{sys_}] ({fit['n_rows']} rows)")
        print(f"  elev bins: {fit['edges']}")
        print(f"  sigma_pr_m: {fit['sigma_pr_m']}")
        print(f"  sigma_td_m: {fit['sigma_td_m']}")


if __name__ == "__main__":
    main()
